- name: fetch configs
  hosts: test8
  gather_facts: false
  become: false

  tasks:

    - name: fetch
      fetch:
        src: "{{ item }}"
        dest: "../configs/"
        flat: true
      with_items:
        - /var/www/html/test8/index.php
        - /etc/nginx/conf.d/default.conf
        - /etc/httpd/conf/httpd.conf
        - /etc/httpd/conf.d/test8.clo.southbridge.ru.conf
        - /etc/httpd/conf.d/php.conf
        - /etc/my.cnf
        - /etc/sysconfig/memcached
        - /etc/php.ini
        - /etc/php-fpm.d/www.conf